joy_node:
  ros__parameters:
    device_id: 0
    dead one: 0.05
    autorepeat_rate: 10.0
    # coalesce_interval: 100

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.06
    scale_linear_turbo:
      x: 0.1

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 0.8

    enable_button: 6
    enable_turbo_button: 7

    require_enable_button: true